In [23]:
import pandas as pd
import math

In [24]:
!pwd

/d/Alex/SLR-Translation/Alex_Karachun

In [44]:
df = pd.read_csv("../../slovo_full/annotations.csv", sep='\t')

In [45]:
df.shape

(20400, 9)

In [52]:
df[df['height'] != 1920]

,attachment_id,text,user_id,height,width,length,train,begin,end
6,cf6845ac-9e02-49b4-8d2b-f56c789f973a,Ц,95af8e702c909eee7145c6dc1a3d756b,1280,720,91.0,True,16,67
58,eb72178c-7020-4cff-9123-2c1a90695d41,З,95af8e702c909eee7145c6dc1a3d756b,1280,720,116.0,True,30,89
59,59cbf994-7b34-4c53-a4a4-b4b1a3169a0e,Х,95af8e702c909eee7145c6dc1a3d756b,1280,720,76.0,True,2,50
60,8d3335ad-5fdb-4804-a1b0-5328bfde4c16,М,95af8e702c909eee7145c6dc1a3d756b,1280,720,73.0,True,13,56
61,d9171a06-bbad-4278-95b7-4e8c1b551e2d,Б,95af8e702c909eee7145c6dc1a3d756b,1280,720,99.0,True,3,79
...,...,...,...,...,...,...,...,...,...
20384,no80610a96-baf8-4e71-9c52-185a8b07b28c,no_event,3018b64d2c938f5b6a0826dfdf486f2c,1080,1920,59.0,False,0,59
20385,no834a06ad-d4ea-4489-ac3a-fea461af51cb,no_event,20f1589682a8e64769ae2ebc21b5fb6b,720,1280,50.0,False,0,50
20388,noddca5921-ec4d-4a2e-b71a-42b904ffc10d,no_event,e258af38a7d5af6b01812276b628203e,720,1280,75.0,False,0,75
20390,no5f74d641-3d32-4f9c-b4b8-44f40693506b,no_event,e258af38a7d5af6b01812276b628203e,720,1280,81.0,False,0,81
20396,no7a7812b1-ae64-4402-9ebc-5b947edbd021,no_event,f5b82a9c82f6d870ec253e4c3fa96d83,1280,720,32.0,False,0,32

In [38]:
df = df[df['height'] > df['width']]

In [39]:
df.shape

(17493, 9)

In [40]:
aspect_ratios = df.groupby(["height", "width"]).size().reset_index(name="count")

# Сортировка по количеству (опционально)
aspect_ratios = aspect_ratios.sort_values(by="count", ascending=False)

print(aspect_ratios)

    height  width  count
11    1920   1080  10300
0     1280    720   4948
4     1920    822   1599
10    1920    960    239
7     1920    886    152
12    1920   1088    118
6     1920    880     52
8     1920    896     32
9     1920    920     23
5     1920    864     15
1     1328    768      5
3     1728   1080      4
2     1644   1080      1
13    1920   1584      1
14    1920   1620      1
15    1920   1634      1
16    1920   1642      1
17    1920   1710      1

In [42]:
aspect_ratios['/'] = aspect_ratios['height'] / aspect_ratios['width']

In [43]:
aspect_ratios

    height  width  count         /
11    1920   1080  10300  1.777778
0     1280    720   4948  1.777778
4     1920    822   1599  2.335766
10    1920    960    239  2.000000
7     1920    886    152  2.167043
12    1920   1088    118  1.764706
6     1920    880     52  2.181818
8     1920    896     32  2.142857
9     1920    920     23  2.086957
5     1920    864     15  2.222222
1     1328    768      5  1.729167
3     1728   1080      4  1.600000
2     1644   1080      1  1.522222
13    1920   1584      1  1.212121
14    1920   1620      1  1.185185
15    1920   1634      1  1.175031
16    1920   1642      1  1.169306
17    1920   1710      1  1.122807